const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Model3D,
		C3.Plugins.Particles,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Sprite.Acts.SetRotationEuler,
		C3.Plugins.Sprite.Exps.RotationY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetRotationType,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value
	];
};
self.C3_JsPropNameTable = [
	{found: 0},
	{Flash: 0},
	{Solid: 0},
	{redpanda: 0},
	{whiteTiger: 0},
	{komodo: 0},
	{midoroHornbill: 0},
	{kakapo: 0},
	{phillpeEagle: 0},
	{orangUtan: 0},
	{Anchor: 0},
	{Tween: 0},
	{AnimalCard: 0},
	{walrus: 0},
	{polar: 0},
	{narwhal: 0},
	{amur: 0},
	{penguin: 0},
	{snowleopard: 0},
	{saiga: 0},
	{Axol: 0},
	{whale: 0},
	{shark: 0},
	{turtle: 0},
	{vaquita: 0},
	{manta: 0},
	{dugong: 0},
	{TiledBackground15: 0},
	{TiledBackground6: 0},
	{solidTree: 0},
	{TiledBackground3: 0},
	{TiledBackground2: 0},
	{TiledBackground7: 0},
	{portalForest: 0},
	{MoveTo: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Stone: 0},
	{ForestCage: 0},
	{RaceIntro: 0},
	{TiledBackground: 0},
	{QUIZFOREST: 0},
	{pos: 0},
	{Bullet: 0},
	{log: 0},
	{ForestRedLine: 0},
	{RaceInstruction: 0},
	{AnsA: 0},
	{AnsB: 0},
	{AnsC: 0},
	{optA: 0},
	{optB: 0},
	{optC: 0},
	{portalForest2: 0},
	{Rotate: 0},
	{Fade: 0},
	{portal: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{TiledBackground12: 0},
	{TiledBackground9: 0},
	{TiledBackground8: 0},
	{portalArtic: 0},
	{click: 0},
	{IcyWalrus: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{IcyWalrus2: 0},
	{IcyWalrus3: 0},
	{WhckInstruction2: 0},
	{WalrusIntro: 0},
	{Sine: 0},
	{iceLayer: 0},
	{iceLayer2: 0},
	{iceLayer3: 0},
	{iceLayer4: 0},
	{button1la: 0},
	{button2so: 0},
	{button3do: 0},
	{button4re: 0},
	{button5mi: 0},
	{button6: 0},
	{button7fa: 0},
	{TiledBackground13: 0},
	{TiledBackground14: 0},
	{Sprite19: 0},
	{portalOcean: 0},
	{btnBack: 0},
	{btnHowtoPlay: 0},
	{btnLoad: 0},
	{btnPlay: 0},
	{TiledBackgroundInstruction: 0},
	{TiledBackgroundlanding: 0},
	{txtInstruction: 0},
	{Mouse: 0},
	{isStunt: 0},
	{TileMovement: 0},
	{ScrollTo: 0},
	{BoundTo: 0},
	{player: 0},
	{Keyboard: 0},
	{Sprite2: 0},
	{countdown: 0},
	{Audio: 0},
	{Sprite5: 0},
	{backgroundquiz1: 0},
	{Question: 0},
	{Text: 0},
	{Array: 0},
	{QuizCongratulations: 0},
	{whitebox: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{WhackSocreTxt: 0},
	{Sprite40: 0},
	{WhackMissedTxt: 0},
	{TiledBackground4: 0},
	{walrusLiveSprite: 0},
	{timerTxt: 0},
	{Sprite41: 0},
	{backgroundquiz2: 0},
	{check: 0},
	{Text3: 0},
	{TiledBackground5: 0},
	{timerBar: 0},
	{timercolor: 0},
	{timercover: 0},
	{"3DModel": 0},
	{turtleNet: 0},
	{speed: 0},
	{scissors: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{turtleIntroBox: 0},
	{turtleIntroTxt: 0},
	{backgroundquiz3: 0},
	{CrystalForest: 0},
	{crystalSnow: 0},
	{crystalOcean: 0},
	{restoration: 0},
	{TiledBackground16: 0},
	{crystalEarth: 0},
	{endingtext: 0},
	{Particles: 0},
	{Sprite4: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{MainTitleFrame: 0},
	{btnSave: 0},
	{exitbtn: 0},
	{restartBtn: 0},
	{TiledBackground17: 0},
	{frame: 0},
	{backFrame: 0},
	{turtleframeCover: 0},
	{Sprite48: 0},
	{SHOWCARD: 0},
	{ForestAnimals: 0},
	{Win: 0},
	{Lose: 0},
	{CurrQ: 0},
	{WalrusMissed: 0},
	{WalrusShow: 0},
	{gameStart: 0},
	{WalrusScore: 0},
	{gameEnd: 0},
	{timer: 0},
	{TurtleClick: 0},
	{secret: 0},
	{answer: 0}
];

self.InstanceType = {
	redpanda: class extends self.ISpriteInstance {},
	whiteTiger: class extends self.ISpriteInstance {},
	komodo: class extends self.ISpriteInstance {},
	midoroHornbill: class extends self.ISpriteInstance {},
	kakapo: class extends self.ISpriteInstance {},
	phillpeEagle: class extends self.ISpriteInstance {},
	orangUtan: class extends self.ISpriteInstance {},
	AnimalCard: class extends self.ISpriteInstance {},
	walrus: class extends self.ISpriteInstance {},
	polar: class extends self.ISpriteInstance {},
	narwhal: class extends self.ISpriteInstance {},
	amur: class extends self.ISpriteInstance {},
	penguin: class extends self.ISpriteInstance {},
	snowleopard: class extends self.ISpriteInstance {},
	saiga: class extends self.ISpriteInstance {},
	Axol: class extends self.ISpriteInstance {},
	whale: class extends self.ISpriteInstance {},
	shark: class extends self.ISpriteInstance {},
	turtle: class extends self.ISpriteInstance {},
	vaquita: class extends self.ISpriteInstance {},
	manta: class extends self.ISpriteInstance {},
	dugong: class extends self.ISpriteInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	solidTree: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	portalForest: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Stone: class extends self.ISpriteInstance {},
	ForestCage: class extends self.ISpriteInstance {},
	RaceIntro: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	QUIZFOREST: class extends self.ISpriteInstance {},
	log: class extends self.ISpriteInstance {},
	ForestRedLine: class extends self.ISpriteInstance {},
	RaceInstruction: class extends self.ITextInstance {},
	AnsA: class extends self.ITextInstance {},
	AnsB: class extends self.ITextInstance {},
	AnsC: class extends self.ITextInstance {},
	optA: class extends self.ISpriteInstance {},
	optB: class extends self.ISpriteInstance {},
	optC: class extends self.ISpriteInstance {},
	portalForest2: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	portalArtic: class extends self.ISpriteInstance {},
	IcyWalrus: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	IcyWalrus2: class extends self.ISpriteInstance {},
	IcyWalrus3: class extends self.ISpriteInstance {},
	WhckInstruction2: class extends self.ITextInstance {},
	WalrusIntro: class extends self.ISpriteInstance {},
	iceLayer: class extends self.ITiledBackgroundInstance {},
	iceLayer2: class extends self.ITiledBackgroundInstance {},
	iceLayer3: class extends self.ITiledBackgroundInstance {},
	iceLayer4: class extends self.ITiledBackgroundInstance {},
	button1la: class extends self.ISpriteInstance {},
	button2so: class extends self.ISpriteInstance {},
	button3do: class extends self.ISpriteInstance {},
	button4re: class extends self.ISpriteInstance {},
	button5mi: class extends self.ISpriteInstance {},
	button6: class extends self.ISpriteInstance {},
	button7fa: class extends self.ISpriteInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	portalOcean: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnHowtoPlay: class extends self.ISpriteInstance {},
	btnLoad: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	TiledBackgroundInstruction: class extends self.ITiledBackgroundInstance {},
	TiledBackgroundlanding: class extends self.ITiledBackgroundInstance {},
	txtInstruction: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	countdown: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	backgroundquiz1: class extends self.ITiledBackgroundInstance {},
	Array: class extends self.IArrayInstance {},
	QuizCongratulations: class extends self.ITextInstance {},
	whitebox: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	WhackSocreTxt: class extends self.ITextInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	WhackMissedTxt: class extends self.ITextInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	walrusLiveSprite: class extends self.ISpriteInstance {},
	timerTxt: class extends self.ITextInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	backgroundquiz2: class extends self.ITiledBackgroundInstance {},
	check: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	timerBar: class extends self.ISpriteInstance {},
	timercolor: class extends self.ISpriteInstance {},
	timercover: class extends self.ISpriteInstance {},
	_3DModel: class extends self.I3DModelInstance {},
	turtleNet: class extends self.ISpriteInstance {},
	scissors: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	turtleIntroBox: class extends self.ISpriteInstance {},
	turtleIntroTxt: class extends self.ITextInstance {},
	backgroundquiz3: class extends self.ITiledBackgroundInstance {},
	CrystalForest: class extends self.ISpriteInstance {},
	crystalSnow: class extends self.ISpriteInstance {},
	crystalOcean: class extends self.ISpriteInstance {},
	restoration: class extends self.ISpriteInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	crystalEarth: class extends self.ISpriteInstance {},
	endingtext: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	MainTitleFrame: class extends self.ISpriteInstance {},
	btnSave: class extends self.ISpriteInstance {},
	exitbtn: class extends self.ISpriteInstance {},
	restartBtn: class extends self.ISpriteInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	frame: class extends self.ISpriteInstance {},
	backFrame: class extends self.ITiledBackgroundInstance {},
	turtleframeCover: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {}
}